version: '3'

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    working_dir: /app
    # command: ["npm", "start"]
